import { UserRole } from "@/utils/enums";

export const mockUserData = {
  teamid: "",
  winteamid: "",
  A: "",
  B: "",
  C: "",
  D: "",
  E: "",
  F: "",
  G: "",
  H: "",
  I: "",
  J: "",
  K: "",
  L: "",
  profitScore: 0,
  availableScore: 0,
  notbetcount: 0,
  groupWinCount: 0,
  couponwin: 0,
  couponlost: 0,
  coupons: 0,
};

export const _mockChatMessages = [
  {
    _id: "1",
    sender: {
      _id: "system",
      username: "system",
      active: true,
      name: "Mokasfoci",
      email: "info@mokasfoci.hu",
      role: UserRole.Admin,
      avatar: "",
      data: mockUserData,
    },
    message:
      "Szia! Miben segíthetek ma? Esetleg kérdésed van a tippeléssel vagy a pontszámítással kapcsolatban?",
    room: "general",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    sender: {
      _id: "user123",
      username: "dezso88",
      active: true,
      name: "Dezső",
      email: "dezso@example.com",
      role: UserRole.User,
      avatar: "",
      data: mockUserData,
    },
    message: "Sziasztok! Mikor lesznek kint a hétvégi meccsek?",
    room: "general",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    sender: {
      _id: "me",
      username: "pro_tippelo",
      active: true,
      name: "Én",
      email: "me@example.com",
      role: UserRole.User,
      avatar: "",
      data: mockUserData,
    },
    message: "Én is várom már őket, remélem hamarosan!",
    room: "general",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "4",
    sender: {
      _id: "user456",
      active: true,
      username: "kovacs_geza",
      name: "Géza",
      email: "geza@example.com",
      role: UserRole.User,
      avatar: "",
      data: mockUserData,
    },
    message: "Szerintem holnap délutánra várhatóak.",
    room: "general",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
